### ISSUE TITLE
CSV Features

### ISSUE THREAD

**Issue by DiegoCatalano** [viniciusbo/svm-text-classification-api#1]
O meu fiii, vc n entra no face, aki vai então.

Salva um CSV ja com as features extraidas (TF-IDT, word2vec), assim eu posso te ajudar tb.

Abraço.

**Comment by viniciusbo** [comment]
Graaande @DiegoCatalano! Correria danada cara, to entrando pouco no Face mesmo.

Vou mandar um CSV com o TF-IDF, valeu a ajuda mestre!

**Comment by DiegoCatalano** [comment]
Demoro, manda seu whats ou telegram se tiver usando para a gente comunicar, vlws
